# Generated by Django 4.2.7 on 2023-11-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_alter_education_end_date_alter_work_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
